---
title: "Preregistration: data extraction from epidemiology articles"
author: "Katie Drax"
date: "9 January 2020"
output: word_document
---

# Time of writing

KD and MG independently identified the study designs (cohort, case-control or cross-sectional) used by each of the 178 "observational epidemiology" articles by completing the Study Design Form for each article. 
In the form, extractors also indicated if all supplementary material can be accessed via University of Bristol subscriptions. 
Any conflicts were discussed by the two extractors and resolved by mutual consent if possible. 
If not resolved after discussion, RR determined the study designs. 
The Study Design Form was hosted on Qualtrics but a PDF version can be found at https://osf.io/nd78g/

The articles were randomly assigned an id number from 1-178.
The articles with an id number between 1 and 80 were selected for the first round of data extraction.
KD was assigned as the first extractor to all 80 articles.
The second extractor was randomly assigned from MG, RR or BW.

The Data Extraction form was hosted on Qualtrics and piloted twice.
In the first, 5 observational epidemiology articles  were piloted by MG, KD and/or RR. 
Major changes were made so the Data Extraction Form will be completed again for the articles in the first pilot.
In the second, KD piloted the changed form on 3 articles.
No changes were made so the responses for articles in the second pilot will be retained.

KD assessed examined the notices attached to the online version of the observational epidemiology articles to identify any retracted articles. None were identified

1 article was incorrectly classified as an 'observational epidemiology' study so 177 observational epidemiology articles remain.

# Data extraction procedure


KD will attempt to retrieve any supplementary material we could not access by contacting the authors. 

The information in Table 1 (attached) will be extracted manually by KD or automatically by Endnote which contains the article's metadata exported from the database the article was located in.

The extractors will independently complete the Data Extraction Form for each article they are assigned. 
Any conflicts will be discussed by the two extractors and resolved by mutual consent if possible. 
If not resolved after discussion, RR or MM will resolve the conflict. 
Articles will continue to be selected at random until none remain, or until the authors resources are exhausted.

*Table 1. Methods for extracting article meta-data*

| Item | Definition | Method of extraction |
| --- | --- | --- |
| Article ID(s) of related articles | Article IDs of articles that contain similar analyses. | Examine articles with same first author, last author and UK Biobank application number. |
| Citation |   | Endnote |
| Publication date |   | Endnote |
| Authors |   |  Endnote |
| Journal |   | Endnote  |
| Volume |   | Endnote  |
| Issue |   | Endnote  |
| Open Access |   | See if can access article on publishing journal's site on a non-university network. If not accessible search for self-archived version on Google Scholar |
| Countries of corresponding author |   | Extract country from author's affiliations |
| UK Biobank Application number | Study's approved UK Biobank data application number (if present) | Search article for all these terms:  'application' , 'approv' , 'number' , 'Resource'. If not found examine any strings of numbers in article |
| Author keywords |   | Search page 1. If not on page 1 search article for 'keywords' |
| Journal endorsement | Journal's endorsement of STROBE before publication | Extract references to STROBE from the journal's most recent 'instructions/guide for authors' before article's publication date |
| Journal impact factor |   | Retrieve the impact factor of the journal for year of publication from Web of Science's Journal Citation Reports (JCR) |
| Corresponding author email address |   | Search article for 'corresponding', '@') |
| Conflicts of interest statement |   | Search article material for all these terms: 'competing', 'interest' ,'conflict' , 'disclosure' |
| Classification | Classification ('mendelian randomisation', 'observational epidemiology' or 'other') as assigned by KD, BW and RR in Rayyan | Rayyan 

# Changes from the preregistered protocol

We will not attempt to retrieve any missing items in the Data Extraction Form, in order to give an accurate assessment of the version of record and to avoid exhausting the extractors resources.